server:
  port: 8080
database: 
  - user: admin
    password: admin 
    host: localhost
    dbName: shopDEV 
  - user: order
    password: order
    host: localhost
    dbName: order

security:
  jwt:
    key: abc123 

Redis: 
  user: admin
elasticsearch:
  user: admin
rabittMQ:
  user: admin
kafka:
  user: admin
